class ShopItem {
  final String id, name, category, description, icon;
  final int price;
  final bool repeatable;
  const ShopItem({
    required this.id,
    required this.name,
    required this.category,
    required this.price,
    required this.description,
    required this.icon,
    this.repeatable = false,
  });
}

List<ShopItem> shopCatalog = <ShopItem>[
  ShopItem(
    id: 'cozy_room',
    name: 'Cozy Room',
    category: 'Homes',
    price: 500,
    description: 'A warm place to recharge.',
    icon: '🏠',
  ),
  ShopItem(
    id: 'small_apartment',
    name: 'Small Apartment',
    category: 'Homes',
    price: 2000,
    description: 'Your first independent space.',
    icon: '🏢',
  ),
  ShopItem(
    id: 'family_house',
    name: 'Family House',
    category: 'Homes',
    price: 5000,
    description: 'Room to grow together.',
    icon: '🏡',
  ),
  ShopItem(
    id: 'dream_villa',
    name: 'Dream Villa',
    category: 'Homes',
    price: 15000,
    description: 'A home for your biggest dreams.',
    icon: '🏰',
  ),
  ShopItem(
    id: 'bicycle',
    name: 'Bicycle',
    category: 'Vehicles',
    price: 300,
    description: 'A fresh-air ride.',
    icon: '🚲',
  ),
  ShopItem(
    id: 'scooter',
    name: 'Scooter',
    category: 'Vehicles',
    price: 1000,
    description: 'Move through the day with ease.',
    icon: '🛵',
  ),
  ShopItem(
    id: 'car',
    name: 'Car',
    category: 'Vehicles',
    price: 5000,
    description: 'A dependable journey.',
    icon: '🚗',
  ),
  ShopItem(
    id: 'sports_car',
    name: 'Sports Car',
    category: 'Vehicles',
    price: 15000,
    description: 'Drive toward the extraordinary.',
    icon: '🏎️',
  ),
  ShopItem(
    id: 'dog',
    name: 'Dog',
    category: 'Pets',
    price: 1500,
    description: 'A loyal companion.',
    icon: '🐶',
  ),
  ShopItem(
    id: 'cat',
    name: 'Cat',
    category: 'Pets',
    price: 1500,
    description: 'A curious companion.',
    icon: '🐱',
  ),
  ShopItem(
    id: 'golden_retriever',
    name: 'Golden Retriever',
    category: 'Pets',
    price: 3000,
    description: 'An extra dose of sunshine.',
    icon: '🐕',
  ),
  ShopItem(
    id: 'desk',
    name: 'Desk',
    category: 'Furniture',
    price: 300,
    description: 'Make room for meaningful work.',
    icon: '🪑',
  ),
  ShopItem(
    id: 'gaming_setup',
    name: 'Gaming Setup',
    category: 'Furniture',
    price: 1000,
    description: 'A space for play and creativity.',
    icon: '🖥️',
  ),
  ShopItem(
    id: 'sofa',
    name: 'Sofa',
    category: 'Furniture',
    price: 500,
    description: 'A soft landing after a focused day.',
    icon: '🛋️',
  ),
  ShopItem(
    id: 'bookshelf',
    name: 'Bookshelf',
    category: 'Furniture',
    price: 400,
    description: 'Keep your curiosity close.',
    icon: '📚',
  ),
  ShopItem(
    id: 'vacation_trip',
    name: 'Vacation Trip',
    category: 'Lifestyle',
    price: 3000,
    description: 'A well-earned change of scenery.',
    icon: '✈️',
  ),
  ShopItem(
    id: 'beach_house_upgrade',
    name: 'Beach House Upgrade',
    category: 'Lifestyle',
    price: 8000,
    description: 'Let the horizon inspire you.',
    icon: '🌴',
  ),
  ShopItem(
    id: 'private_workspace',
    name: 'Private Workspace',
    category: 'Lifestyle',
    price: 2500,
    description: 'A room dedicated to your craft.',
    icon: '🧑‍💻',
  ),
];
