import 'package:flutter/material.dart';
import 'models/focus_session.dart';
import 'models/stage7.dart';
import 'services/stage7_storage.dart';
import 'services/focus_statistics.dart';

class GoalsPage extends StatefulWidget { final List<FocusSession> sessions; const GoalsPage({super.key, required this.sessions}); @override State<GoalsPage> createState() => _GoalsPageState(); }
class _GoalsPageState extends State<GoalsPage> {
  final storage = Stage7Storage(); UserGoals goals = const UserGoals(); bool loading = true;
  @override void initState() { super.initState(); storage.loadGoals().then((v) { if (mounted) setState(() { goals = v; loading = false; }); }); }
  String duration(Duration d) => d.inHours > 0 ? '${d.inHours}h ${d.inMinutes % 60}m' : '${d.inMinutes}m';
  Future<void> edit() async { final d = TextEditingController(text: '${goals.dailyTargetMinutes}'), w = TextEditingController(text: '${goals.weeklyTargetMinutes}'); final result = await showDialog<UserGoals>(context: context, builder: (_) => AlertDialog(title: const Text('Edit your goals'), content: Column(mainAxisSize: MainAxisSize.min, children: [TextField(controller: d, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'Daily minutes')), TextField(controller: w, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'Weekly minutes'))]), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')), FilledButton(onPressed: () { final daily = int.tryParse(d.text), weekly = int.tryParse(w.text); if (daily == null || weekly == null || daily < 1 || weekly < 1 || daily > 1440 || weekly > 10080) return; Navigator.pop(context, UserGoals(dailyTargetMinutes: daily, weeklyTargetMinutes: weekly)); }, child: const Text('Save'))])); if (result != null) { final saved = await storage.saveGoals(result); if (mounted) setState(() => goals = saved); } }
  @override Widget build(BuildContext context) { if (loading) return const Center(child: CircularProgressIndicator()); final mobile = MediaQuery.sizeOf(context).width < 700; final today = FocusStatistics.today(widget.sessions), week = FocusStatistics.thisWeek(widget.sessions); return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Flex(direction: mobile ? Axis.vertical : Axis.horizontal, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [const Text('Goals', style: TextStyle(fontSize: 30, fontWeight: FontWeight.w800)), if (mobile) const SizedBox(height: 12), OutlinedButton.icon(onPressed: edit, icon: const Icon(Icons.edit), label: const Text('Edit goals'))]), const SizedBox(height: 8), const Text('Small, consistent focus adds up to a life you love.'), const SizedBox(height: 24), _GoalCard(title: "TODAY'S GOAL", target: Duration(minutes: goals.dailyTargetMinutes), focused: today), const SizedBox(height: 16), _GoalCard(title: "THIS WEEK'S GOAL", target: Duration(minutes: goals.weeklyTargetMinutes), focused: week), const SizedBox(height: 18), Text('🔥 ${Stage7Calculations.currentStreak(widget.sessions)} day streak', style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w700)), Text('Longest: ${Stage7Calculations.longestStreak(widget.sessions)} days', style: const TextStyle(color: Colors.grey))]); }
}
class _GoalCard extends StatelessWidget { final String title; final Duration target, focused; const _GoalCard({required this.title, required this.target, required this.focused}); @override Widget build(BuildContext context) { final double ratio = target.inSeconds == 0 ? 0.0 : (focused.inSeconds / target.inSeconds).clamp(0.0, 1.0).toDouble(); final complete = focused >= target; return Card(child: Padding(padding: const EdgeInsets.all(22), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: const TextStyle(letterSpacing: 1.2, fontWeight: FontWeight.w800, color: Colors.grey)), const SizedBox(height: 16), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text('Target: ${target.inHours > 0 ? '${target.inHours}h ${target.inMinutes % 60}m' : '${target.inMinutes}m'}'), Text('Focused: ${focused.inHours > 0 ? '${focused.inHours}h ${focused.inMinutes % 60}m' : '${focused.inMinutes}m'}')]), const SizedBox(height: 12), LinearProgressIndicator(value: ratio, minHeight: 10, borderRadius: BorderRadius.circular(8)), const SizedBox(height: 10), Text(complete ? '🎯 Goal completed!' : 'Progress: ${(ratio * 100).round()}% · Remaining: ${focused >= target ? '0m' : '${(target - focused).inMinutes}m'}', style: const TextStyle(fontWeight: FontWeight.w600))]))); } }
